### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by 1010075746** [TimandXiyu/SANet-style-transfer#1]
RuntimeError: The size of tensor a (89) must match the size of tensor b (90) at non-singleton dimension 3

**Comment by TimandXiyu** [comment]
Please provide more info about what kind of data you are inputing to the model to me.
The code works fine for my 1024*1024 image data.

I am guessing your input pairs might not actually have exactly the same dimension. Simple resize function should fix it.

FYI, this repo is mainly repo for some part of my thesis, you might need to change some variables to suit your python env.

**Comment by 1010075746** [comment]
Thanks for your help. I succeed after changing the size of input image.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TimandXiyu/SANet-style-transfer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月12日(星期一) 下午4:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TimandXiyu/SANet-style-transfer] RuntimeError (#1)





 
Please provide more info about what kind of data you are inputing to the model to me.
 The code works fine for my 1024*1024 image data.
 
I am guessing your input might not actually have exactly the same dimension. Simple resize function should fix it.
